Street 0, Cluster 152, Actions taken 1, Last Action ai Other pip 400
Traceback (most recent call last):
  File "/Users/hcs/Downloads/pokerbots-2025/python_skeleton/player.py", line 663, in <module>
    run_bot(Player(), parse_args())
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hcs/Downloads/pokerbots-2025/python_skeleton/skeleton/runner.py", line 142, in run_bot
    runner.run()
    ~~~~~~~~~~^^
  File "/Users/hcs/Downloads/pokerbots-2025/python_skeleton/skeleton/runner.py", line 117, in run
    action = self.pokerbot.get_action(game_state, round_state, active)
  File "/Users/hcs/Downloads/pokerbots-2025/python_skeleton/player.py", line 503, in get_action
    down_id = encode_node(og_cluster, actions_taken, last_action, allowed_pips[down])
                                                                  ~~~~~~~~~~~~^^^^^^
IndexError: list index out of range
